# 单独把语言文件拿出来

default_lang = {
    "lang-version": "1.1.7",
    "language": "English",
    "查询玩家&部分实体行为记录 --格式 /ty x坐标 y坐标 z坐标 时间(单位:小时) 半径": "Query player & partial entity behavior records -- Format: /ty x-coordinate y-coordinate z-coordinate Time (in hours) Radius",
    "查看天眼命令帮助信息": "View Tianyan command help information",
    "封禁一名玩家(仅管理员可用)": "Ban a player (OP only)",
    "从黑名单中移除玩家(仅管理员可用)": "Remove a player from the blacklist (OP only)",
    "列出所有加入黑名单的玩家(仅管理员可用)": "List all players added to the blacklist (OP only)",
    "封禁设备ID(仅管理员可用)": "Ban a device ID (OP only)",
    "从设备黑名单移除设备ID(仅管理员可用)": "Remove a device ID from the blacklist (OP only)",
    "列出所有加入黑名单的设备ID(仅管理员可用)": "List all device IDs added to the blacklist (OP only)",
    "关键词搜索 --格式 /tys 搜索类型  查询关键词 时间(单位:小时) (仅管理员可用)": "Keyword search -- Format: /tys search type query keyword Time (in hours) (OP only)",
    "使用图形窗口查询玩家&部分实体行为记录": "Use GUI to query player & partial entity behavior records",
    "使用图形窗口搜索关键词查询玩家&部分实体行为记录": "Use GUI for keyword search to query player & partial entity behavior records",
    "实验性功能 还原玩家直接方块放置破坏行为和实体爆炸破坏 --格式 /tyback 坐标 时间(单位:小时) 半径 实施行为的玩家名或爆炸的实体ID(可选)(仅管理员可用)": "Experimental feature: Restore direct player block placement or destruction and entity explosion damage -- Format: /tyback Coordinates Time (in hours) Radius Player Name or the ID of the exploding entity (optional) (OP only)",
    "天眼插件已启用  版本": "TianyanPlugin has been enable  Version",
    "配置文件位于": "Config file is in",  
    "插件语言设定为": "Plugin language set to",
    "其余数据文件位于": "Other data files located at",
    "项目更新地址": "Project update URL",
    "天眼命令使用方法": "Tianyan command usage",
    "使用/tyban 命令将一名玩家加入黑名单 格式 /tyban 玩家名 理由(选填)": "Use /tyban command to add a player to the blacklist. Format: /tyban Player Name Reason (optional)",
    "使用/tyunban 命令将一名玩家移出黑名单 格式 /tyunban 玩家名": "Use /tyunban command to remove a player from the blacklist. Format: /tyunban Player Name",
    "使用/banlist 命令列出所有被加入黑名单的玩家名": "Use /banlist command to list all blacklisted player names",
    "使用/banid 命令将一名玩家的设备加入黑名单(当目标玩家设备在线时添加黑名单无法直接踢出,请使用其它方法踢出该玩家) 格式 /banid 设备ID": "Use /banid command to blacklist a player's device (if the target player's device is online, adding to the blacklist won't directly kick them. Use other methods to kick them). Format: /banid Device ID",
    "使用/unbanid 命令将一名玩家的设备移出黑名单 格式 /unban 设备ID": "Use /unbanid command to remove a player's device from the blacklist. Format: /unban Device ID",
    "使用/banlist 命令列出所有被加入黑名单的玩家的设备ID": "Use /banlist command to list all blacklisted device IDs",
    "使用 /ty 命令查询查询玩家&部分实体行为记录 格式 /ty x坐标 y坐标 z坐标 时间(单位:小时) 半径": "Use /ty command to query player & partial entity behavior records. Format: /ty x-coordinate y-coordinate z-coordinate Time (in hours) Radius",
    "使用 /tys 命令使用关键词查询玩家&部分实体行为记录 格式 关键词搜索 格式 /tys 搜索类型  查询关键词 时间(单位:小时) (仅管理员可用)": "Use /tys command for keyword search to query player & partial entity behavior records. Format: /tys search type query keyword Time (in hours) (OP only)",
    "使用/tygui 命令使用图形窗口查询玩家&部分实体行为记录": "Use /tygui command to query player & partial entity behavior records via GUI",
    "使用/tysgui 命令使用图形窗口搜索关键词查询玩家&部分实体行为记录 (仅管理员可用)": "Use /tysgui command for keyword search to query player & partial entity behavior records via GUI (OP only)",
    "tys命令参数解析 搜索类型:player action object(玩家或行为实施者 行为 被实施行为的对象) 搜索关键词:玩家名或行为实施者名 交互 破坏 攻击 放置 被实施行为的对象名": "tys command parameters: Search type: player, action, object (Player or action initiator, Action, Targeted object). Keywords: Player name or action initiator name, Interaction, Destruction, Attack, Placement, Targeted object name",
    "实验性功能 使用/tyback 命令还原玩家直接方块放置破坏行为和实体爆炸破坏 格式 /tyback 坐标 时间(单位:小时) 半径 实施行为的玩家名或爆炸的实体ID(可选)(仅管理员可用)": "Experimental feature: Use /tyback command to restore direct player block placement or destruction and entity explosion damage. Format: /tyback Coordinates Time (in hours) Radius Player Name or the ID of the exploding entity (optional) (OP only)",
    "命令格式错误!请检查命令是否正确;如果使用~ ~ ~,请直接输入坐标": "Command format error! Please check if the command is correct; if using ~ ~ ~, input coordinates directly",
    "查询半径最大值为100 !": "Query radius max value is 100!",
    "未查询到任何结果.": "No results found.",
    "已为您查询到此坐标半径": "Found records for this coordinate radius",
    "格": " blocks",
    "小时内的玩家&部分实体行为记录": "hours ago about player & partial entity behavior records",
    "请通过弹窗查看": "Please check the popup window",
    "行为实施者": "Action initiator",
    "行为": "Action",
    "坐标": "Coordinates",
    "时间": "Time",
    "对象类型": "Object type",
    "维度": "Dimension",
    "下一页": "Next page",
    "上一页": "Previous page",
    "半径": "Radius",
    "小时内的查询记录-第": "hours ago query records - The ",
    "页": " Page",
    "小时内的查询记录": "hours ago query records",
    "格式错误": "Format error",
    "玩家": "Player ",
    "已经在": "Already in ",
    "被添加至黑名单中了,理由是:": "been added to the blacklist, the reason is:",
    "请勿重复添加": "Do not add repeatedly",
    "已被加入黑名单,理由": "has been blacklisted, reason:",
    "理由": "Reason",
    "黑名单文件不存在,已自动创建": "Blacklist file does not exist, automatically created",
    "已从黑名单中删除": "removed from the blacklist",
    "不存在于黑名单中": "does not exist in the blacklist",
    "黑名单文件不存在": "Blacklist file does not exist",
    "黑名单中没有玩家": "No players in the blacklist",
    "于": "on",
    "被封禁,理由": "Banned, reason:",
    "设备ID": "Device ID",
    "被添加至设备ID黑名单中了,请勿重复添加": "been added to the device ID blacklist, do not add repeatedly",
    "已被加入黑名单": "has been added to the blacklist",
    "设备ID黑名单文件不存在,已自动创建": "Device ID blacklist file does not exist, automatically created",
    "设备黑名单文件不存在": "Device blacklist file does not exist",
    "没有设备在黑名单中": "No devices in the blacklist",
    "被封禁": "been banned",
    "命令格式错误!请检查命令是否正确": "Command format error! Please check if the command is correct",
    "命令格式错误!未知的参数": "Command format error! Unknown parameter",
    "已为您查询到关键词": "Found records for the keyword",
    "的以下相关内容": "with the following related content",
    "小时内的记录-第": "hours ago records - The ",
    "小时内的记录": "hours ago records",
    "控制台无法使用该命令": "This command cannot be used in the console",
    "天眼查询菜单": "Tianyan query menu",
    "输入查询坐标": "Enter query coordinates",
    "输入查询时间(单位小时)": "Enter query time (in hours)",
    "输入查询半径": "Enter query radius",
    "天眼关键词查询菜单": "Tianyan keyword query menu",
    "选择搜索类型(玩家或行为实施者 行为 被实施行为的对象)": "Select search type (Player or action initiator, Action, Target object)",
    "关键词": "Keyword",
    "输入查询关键词": "Enter query keyword",
    "半径最大值为100 !": "Maximum radius is 100!",
    "无记录数据": "No record data",
    "开始还原": "Start restoration",
    "小时内的方块": "hours ago Blocks",
    "在": "at",
    "使用": "Use",
    "交互": "Interact",
    "破坏": "Destroy",
    "放置": "Place",
    "攻击": "Attack",
    "你因涉嫌短时间内发送多条命令被ban": "You have been banned for sending multiple commands in a short time",
    "因涉嫌短时间内发送多条命令被ban": "Banned for sending multiple commands in a short time",
    "你因涉嫌短时间内发送多条消息被ban": "You have been banned for sending multiple messages in a short time",
    "因涉嫌短时间内发送多条消息被ban": "Banned for sending multiple messages in a short time",
    "你已被封禁,理由": "You have been banned, reason:",
    "被封禁时间": "Ban time",
    "处于封禁名单中,已被踢出,封禁理由为": "On the ban list and kicked out, ban reason:",
    "你的设备已于": "Your device has been",
    "被封禁的设备ID": "Banned device ID",
    "试图加入服务器,已被踢出": "Attempted to join the server, kicked out",
    "系统名称": "System name",
    "加入了游戏": "joined the game",
    "物品槽位": "Item Slot",
    "物品名称": "Item Name",
    "数量": "Quantity",
    "的物品栏": "'s Inventory",
    "搜查玩家物品栏 --格式 /tyo 玩家名": "Search player inventory -- format /tyo playername",
    "使用 /tyo 命令查看玩家物品栏 格式 /tyo 玩家名": "Use the /tyo command to view a player's inventory -- format: /tyo playername",
    "命令错误,请检查参数及玩家是否在线": "Error: Command error. Please check the parameters and ensure the player is online.",
    "此玩家的物品栏里没有东西": "This player's inventory is empty.",
    "清理数据库 --格式 /tyclean 时间": "Clean database -- Format: /tyclean time",
    "参数错误": "Invalid parameters",
    "数据库清理发生了未知错误": "An unknown error occurred during database cleaning",
    "清理完成,数据库文件已整理": "Cleaning completed, database files have been organized",
    "发生错误": "Error occurred",
    "已删除": "Deleted ",
    "这些数据超过": "These data exceed ",
    "小时": " hours",
    "已重构数据库释放空间": "Database has been restructured to free up space",
    "行": " lines",
    "\n\n天眼插件更新检测:\n插件版本与最新版本不符,请检查更新.最新版本为": "\n\nTianyan Plugin Update Check:\nThe plugin version does not match the latest version, please check for updates. The latest version is",
    "\n\n天眼插件更新检测:\n无法获取最新版本信息\n": "\n\nTianyan Plugin Update Check:\nUnable to retrieve the latest version information\n",
    "\n\n天眼插件更新检测:\n更新检测超时\n": "\n\nTianyan Plugin Update Check:\nUpdate check timed out\n",
    "\n\n天眼插件更新检测:\n检测更新时发生未知错误": "\n\nTianyan Plugin Update Check:\nAn unknown error occurred while checking for updates",
    "检测实体密度最高的区域 --格式 /tydensity 区域大小": "Detect the area with the highest entity density -- format: /tydensity area_size",
    "最高密度区域在维度": "The highest density area is in the dimension",
    "中点坐标": "Midpoint coordinates",
    "实体数量": "Number of entities",
    "数量最多的实体": "Entity with the most quantity",
    "随机实体位置": "Random entity position",
    "当前没有检测到实体": "No entities detected at the moment",
    "实体密度检测结果": "Entity density detection results",
    "传送到该区域": "Teleport to this area",
    "打印信息到聊天栏": "Print information to the chat bar",
    "未提供参数,使用默认参数20格区域计算": "Parameters not provided, using default parameters for a 20-block area calculation",
    "使用 /tydensity 命令检测实体密度最高的区域 --格式 /tydensity 区域大小 (仅管理员可用)": "Use the /tydensity command to detect the area with the highest entity density -- format: /tydensity area_size (OP only)",
    "使用 /tyclean命令清理数据库中超过一定时间的数据 --格式 /tyclean 时间 (仅管理员可用)": "Use the /tyclean command to clean up data in the database that exceeds a certain time period -- Format: /tyclean time (OP only)",
    "爆炸": "exploded"
}